name: chimera
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - appdirs=1.4.4=pyh9f0ad1d_0
  - beautifulsoup4=4.10.0=pyha770c72_0
  - biopython=1.79=py37h5e8e339_0
  - bioservices=1.8.2=pyhd8ed1ab_0
  - brotlipy=0.7.0=py37h5e8e339_1001
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2021.10.8=ha878542_0
  - certifi=2021.10.8=py37h89c1867_0
  - chardet=4.0.0=py37h89c1867_1
  - colorama=0.4.4=pyh9f0ad1d_0
  - colorlog=6.5.0=py37h89c1867_0
  - cryptography=3.4.8=py37h5d9358c_0
  - diamond=0.9.14=h2e03b76_4
  - easydev=0.10.1=pyh9f0ad1d_0
  - gevent=21.1.2=py37h27cfd23_1
  - greenlet=0.4.17=py37h5e8e339_2
  - grequests=0.6.0=pyh9f0ad1d_0
  - icu=68.1=h58526e2_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libblas=3.9.0=11_linux64_openblas
  - libcblas=3.9.0=11_linux64_openblas
  - libev=4.33=h516909a_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=11.2.0=h69a702a_11
  - libgfortran5=11.2.0=h5c6108e_11
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=11_linux64_openblas
  - libopenblas=0.3.17=pthreads_h8fe5266_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libuv=1.42.0=h7f98852_0
  - libxml2=2.9.12=h72842e0_0
  - libxslt=1.1.33=h15afd5d_2
  - lxml=4.6.3=py37h77fd288_0
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1l=h7f8727e_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pip=21.0.1=py37h06a4308_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyopenssl=21.0.0=pyhd8ed1ab_0
  - pysocks=1.7.1=py37h89c1867_3
  - python=3.7.11=h12debd9_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.7=2_cp37m
  - pytz=2021.3=pyhd8ed1ab_0
  - readline=8.1=h27cfd23_0
  - requests=2.26.0=pyhd8ed1ab_0
  - requests_cache=0.4.13=py_0
  - setuptools=58.0.4=py37h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - soupsieve=2.0.1=py_1
  - sqlite=3.36.0=hc218d9a_0
  - suds-community=0.8.5=pyhd8ed1ab_0
  - tk=8.6.11=h1ccaba5_0
  - urllib3=1.26.7=pyhd8ed1ab_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - wrapt=1.12.1=py37h5e8e339_3
  - xmltodict=0.12.0=py_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zope.event=4.5.0=pyh9f0ad1d_0
  - zope.interface=5.4.0=py37h5e8e339_0
  - pip:
    - anyio==3.3.3
    - argcomplete==1.12.3
    - argon2-cffi==21.1.0
    - atomicwrites==1.4.0
    - attrs==21.2.0
    - backcall==0.2.0
    - bleach==4.1.0
    - carveme==1.5.1
    - cffi==1.15.0
    - charset-normalizer==2.0.7
    - cobra==0.22.1
    - commonmark==0.9.1
    - debugpy==1.5.0
    - decorator==5.1.0
    - defusedxml==0.7.1
    - depinfo==1.7.0
    - diskcache==5.2.1
    - entrypoints==0.3
    - escher==1.7.3
    - future==0.18.2
    - h11==0.12.0
    - httpcore==0.13.7
    - httpx==0.20.0
    - idna==3.3
    - importlib-metadata==4.8.1
    - importlib-resources==5.2.2
    - ipykernel==6.4.1
    - ipython==7.28.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - jedi==0.18.0
    - jinja2==2.11.3
    - jsonschema==3.2.0
    - jupyter-client==7.0.6
    - jupyter-core==4.8.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.2
    - markupsafe==2.0.1
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - more-itertools==8.10.0
    - mpmath==1.2.1
    - nbclient==0.5.4
    - nbconvert==6.2.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - notebook==6.4.4
    - numpy==1.21.2
    - optlang==1.5.2
    - packaging==21.0
    - pandas==1.3.3
    - pandocfilters==1.5.0
    - parso==0.8.2
    - pickleshare==0.7.5
    - pluggy==0.13.1
    - prometheus-client==0.11.0
    - prompt-toolkit==3.0.20
    - psamm==1.1.2
    - git+https://github.com/zhanglab/psamm-import.git
    - py==1.10.0
    - pydantic==1.8.2
    - pygments==2.10.0
    - pyparsing==2.4.7
    - pyrsistent==0.18.0
    - pytest==4.6.11
    - python-libsbml==5.19.0
    - pyyaml==6.0b1
    - pyzmq==22.3.0
    - reframed==1.2.1
    - rfc3986==1.5.0
    - rich==10.12.0
    - ruamel-yaml==0.17.16
    - ruamel-yaml-clib==0.2.6
    - scipy==1.7.1
    - send2trash==1.8.0
    - sniffio==1.2.0
    - swiglpk==5.0.3
    - sympy==1.9
    - terminado==0.12.1
    - testpath==0.5.0
    - tornado==6.1
    - traitlets==5.1.0
    - typing-extensions==3.10.0.2
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - xlrd==2.0.1
    - xlsxwriter==3.0.1
    - zipp==3.6.0